# Assignment 2

## Naive Bayes

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('students.csv')

In [3]:
df

Name        GPA Effort Hirable
0  Sarah       poor   lots     Yes
1   Dana    average   some      No
2   Alex    average   some      No
3  Annie    average   lots     Yes
4  Emily  excellent   lots     Yes
5   Pete  excellent   lots      No
6   John  excellent   lots      No
7  Kathy       poor   some      No

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
df['Hirable'] = LabelEncoder().fit_transform(df['Hirable'])

In [6]:
features = ['GPA', 'Effort']
encoders = dict.fromkeys(features)

for key in encoders.keys():
    encoders[key] = LabelEncoder()
    df[key] = encoders[key].fit_transform(df[key])

In [7]:
df

Name  GPA  Effort  Hirable
0  Sarah    2       0        1
1   Dana    0       1        0
2   Alex    0       1        0
3  Annie    0       0        1
4  Emily    1       0        1
5   Pete    1       0        0
6   John    1       0        0
7  Kathy    2       1        0

In [8]:
from sklearn.naive_bayes import MultinomialNB

In [9]:
mnb = MultinomialNB()
mnb.fit(df[features], df['Hirable'])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [10]:
X_raw = {'GPA': 'poor', 'Effort': 'lots'}
X = {}
for key, encoder in encoders.items():
    X[key] = encoder.transform([ X_raw[key] ])[0]

X

{'GPA': 2, 'Effort': 0}

In [11]:
mnb.predict([list(X.values())])[0]

1

## Association Rule Learning

In [2]:
from apyori import apriori

In [1]:
records = [
    [1,2,3,4,5], [1,2,5], [1,2,3], [1,2,4], [2,3,4], [2,4,5], [1,3], [3,4]
]

In [3]:
min_support = 4/len(records)
min_support

0.5

In [4]:
rules = apriori(records, min_support=min_support)
results = list(rules)  

In [5]:
results[0]

RelationRecord(items=frozenset({1}), support=0.625, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1}), confidence=0.625, lift=1.0)])

In [6]:
for item in results:

    print("Rule: " + str(item[2][0][0]) + " -> " + str(item[2][0][1]))

    print("Support: " + str(item[1]))

    print("Confidence: " + str(item[2][0][2]))
    print("Lift: " + str(item[2][0][3]))
    print("=====================================")

Rule: frozenset() -> frozenset({1})
Support: 0.625
Confidence: 0.625
Lift: 1.0
Rule: frozenset() -> frozenset({2})
Support: 0.75
Confidence: 0.75
Lift: 1.0
Rule: frozenset() -> frozenset({3})
Support: 0.625
Confidence: 0.625
Lift: 1.0
Rule: frozenset() -> frozenset({4})
Support: 0.625
Confidence: 0.625
Lift: 1.0
Rule: frozenset() -> frozenset({1, 2})
Support: 0.5
Confidence: 0.5
Lift: 1.0
Rule: frozenset() -> frozenset({2, 4})
Support: 0.5
Confidence: 0.5
Lift: 1.0


## K-Means Clustering

Code updated for Question 6 in the final exam.

In [2]:
from sklearn.cluster import KMeans
import numpy as np

In [3]:
data = [(3,6), (2,2), (2,0), (0,3), (6,6)]

In [5]:
num_clusters = 2
seeds = np.array([[2,0], [6,6]])

In [6]:
model = KMeans(n_clusters=num_clusters, init=seeds)
model.fit(data)

KMeans(algorithm='auto', copy_x=True, init=array([[2, 0],
       [6, 6]]),
       max_iter=300, n_clusters=2, n_init=10, n_jobs=None,
       precompute_distances='auto', random_state=None, tol=0.0001, verbose=0)

In [7]:
model.cluster_centers_

array([[1.33333333, 1.66666667],
       [4.5       , 6.        ]])

In [8]:
model.labels_

array([1, 0, 0, 0, 1])

In [9]:
df = pd.DataFrame({'coord': data})
df.index += 1
df.rename('A{}'.format, inplace=True)

In [10]:
for i in range(num_clusters):
    df['dist' + str(i+1)] = df['coord'].apply(lambda x: np.linalg.norm(x-seeds[i]))

In [11]:
df['y'] = df.iloc[:, 1:].idxmin(axis=1).str[-1].astype(int)

In [12]:
df

coord     dist1     dist2  y
A1  (3, 6)  6.082763  3.000000  2
A2  (2, 2)  2.000000  5.656854  1
A3  (2, 0)  0.000000  7.211103  1
A4  (0, 3)  3.605551  6.708204  1
A5  (6, 6)  7.211103  0.000000  2

In [13]:
np.mean(df[df['y'] == 1]['coord'].tolist(), axis=0)

array([1.33333333, 1.66666667])

In [14]:
np.mean(df[df['y'] == 2]['coord'].tolist(), axis=0)

array([4.5, 6. ])

In [14]:
# np.mean(df[df['y'] == 3]['coord'].tolist(), axis=0)

array([1.5, 3.5])

In [15]:
print(df.round(4).to_markdown())

|    | coord   |   dist1 |   dist2 |   y |
|:---|:--------|--------:|--------:|----:|
| A1 | (3, 6)  |  6.0828 |  3      |   2 |
| A2 | (2, 2)  |  2      |  5.6569 |   1 |
| A3 | (2, 0)  |  0      |  7.2111 |   1 |
| A4 | (0, 3)  |  3.6056 |  6.7082 |   1 |
| A5 | (6, 6)  |  7.2111 |  0      |   2 |
