In [1]:
import pandas as pd
import numpy as np

In [2]:
# load 'iris' dataset
Iris = pd.read_csv('iris 3 Groups.csv')

In [3]:
Iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   sapallength  150 non-null    float64
 1   sepalwidth   150 non-null    float64
 2   petallength  150 non-null    float64
 3   petalwith    150 non-null    float64
 4   Class        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
Iris.head()

sapallength  sepalwidth  petallength  petalwith        Class
0          5.1         3.5          1.4        0.2  Iris-setosa
1          4.9         3.0          1.4        0.2  Iris-setosa
2          4.7         3.2          1.3        0.2  Iris-setosa
3          4.6         3.1          1.5        0.2  Iris-setosa
4          5.0         3.6          1.4        0.2  Iris-setosa

In [5]:
features = ['sapallength','sepalwidth','petallength','petalwith']

In [6]:
# We will need to build the clustering model using features only, ‘Class’ is used for evaluation purpose later
X = Iris [features]
y = Iris ['Class']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state = 42)

In [9]:
# import KMeans from sklearn
from sklearn.cluster import KMeans

In [10]:
# set number of cluster to be 3
kmeansmodel = KMeans(n_clusters=3)

In [11]:
# fit data
kmeansmodel.fit(X_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

1. n_clusters: The number of clusters to form as well as the number of centroids to generate.
2. init: Method for initialization
3. n_init: Number of time the k-means algorithm will be run with different centroid seeds. The final results will be the best output of n_init consecutive runs in terms of inertia.
4. max_iter: Maximum number of iterations of the k-means algorithm for a single run.

In [12]:
# centroids
centroids = kmeansmodel.cluster_centers_
centroids

array([[5.7972973 , 2.69459459, 4.34864865, 1.42432432],
       [4.94444444, 3.33333333, 1.46296296, 0.24074074],
       [6.75769231, 3.08846154, 5.60384615, 2.02307692]])

In [13]:
# number of iterations
num_iterations = kmeansmodel.n_iter_
num_iterations

2

In [14]:
# Sum of squared distances of samples to their closest cluster center
SSD = kmeansmodel.inertia_
SSD

46.44977323477323

In [15]:
# Transform X to a cluster-distance space
distance = kmeansmodel.transform(X_train)
distance[:5]

array([[0.83538   , 4.0599452 , 0.95160251],
       [2.99784071, 0.46687238, 4.579487  ],
       [3.12777795, 0.36692845, 4.73832261],
       [2.95338016, 0.38563008, 4.51137123],
       [0.27660152, 3.07315247, 1.9961909 ]])

In [16]:
trainlabels = pd.DataFrame(kmeansmodel.labels_,y_train,columns=['cluster'])
trainlabels.head()

cluster
Class                   
Iris-virginica         0
Iris-setosa            1
Iris-setosa            1
Iris-setosa            1
Iris-versicolor        0

In [17]:
Iris_virginica = trainlabels.loc['Iris-virginica']
Iris_setosa = trainlabels.loc['Iris-setosa']
Iris_versicolor = trainlabels.loc['Iris-versicolor']

In [18]:
Iris_virginica.iloc[:, 0].value_counts()

2    23
0     9
Name: cluster, dtype: int64

In [19]:
Iris_setosa.iloc[:, 0].value_counts()

1    27
Name: cluster, dtype: int64

In [20]:
Iris_versicolor.iloc[:, 0].value_counts()

0    28
2     3
Name: cluster, dtype: int64

In [21]:
# predict cluster
testlabels = kmeansmodel.predict(X_test)
testlabels

array([0, 1, 2, 0, 2, 1, 0, 2, 0, 0, 2, 1, 1, 1, 1, 0, 2, 0, 0, 2, 1, 0,
       1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 1, 0, 0, 2, 1,
       1, 0, 2, 2, 0, 2, 0, 2, 0, 1, 2, 0, 1, 1, 1, 0])

In [22]:
testdata=pd.DataFrame(testlabels,y_test,columns=['cluster assignment'])
testdata.head()

cluster assignment
Class                              
Iris-versicolor                   0
Iris-setosa                       1
Iris-virginica                    2
Iris-versicolor                   0
Iris-versicolor                   2

In [23]:
Iris_virginica_test = testdata.loc['Iris-virginica']
Iris_setosa_test = testdata.loc['Iris-setosa']
Iris_versicolor_test = testdata.loc['Iris-versicolor']

In [24]:
Iris_virginica_test.iloc[:, 0].value_counts()

2    16
0     2
Name: cluster assignment, dtype: int64

In [25]:
Iris_setosa_test.iloc[:, 0].value_counts()

1    23
Name: cluster assignment, dtype: int64

In [26]:
Iris_versicolor_test.iloc[:, 0].value_counts()

0    17
2     2
Name: cluster assignment, dtype: int64